from typing import List, Dict


# NOTE: formatting the following list and dicts will mess with the whitespace of the final message sent.
easter_eggs = {
    "dude random": "dude random is the best fucking youtuber seriously man wth. <:yoyo:838836197055922177> <:dadude:838834466289090640>",
    "suketu patni gaming": f"suketu pati gayming channel hits 69420 billion subscibers !!!!!1!1111!111 {'<:hmm:838812033759707176>' * 3}",
    "anhad": f"lionl anhdad fotnite gaying channel hit 69 subs!!! {'<:op:844131961949388841>' * 50 }",
    "jaggu": "jaggu bandar is so mast kalandar that he committed mass genocide <:colgate:844166443583275019>",
    "jediporg": "jihadi p**n barah suprmacy !!!1!1111 katihar chalenge ;) ;) karachi boizzzzzzzzzzz <:mishbadababy:838806751188484167><:mishbadababy:838806751188484167><:convertible:845722150789971988><:convertible:845722150789971988>",
    "mighty raju": f"maity raju supremacy. M SE HOTA HAI MAITY R SE HOTA HAI RAJU RAJU RAJU RAJu {'<:shaktiman:844258104299225118>' * 3}",
    "motu": "Motu Patlu: The best anime of all time. I want to shed light onto the uncultured swines who do not know of the Indian anime Motu Patlu. Motu Patlu is a anime with the characters Motu, Patlu and the citizens of their suburban indian residence. Motu is a thicc boy-o who everybody loves because he is motu. Patlu is motu's sidekick who thinks he is such a smarty pants. Motu saves his town from the villanous John the Dohn. John is a stupid bully who picks on motu using india's own professor jhatika's gadjets against motu. Motu always wins because he is best boy-o. Like in many other animes the characters get different forms and motu patlu is no exception. Motu has many forms some including SUPER DOG MAN MOTU!, Onion Motu, Regular Motu and his final form..... He can only enter his final form when he eats a samosa his favorite snack which he eats on a frequent basis. His final form can sent someone 5x his weight flying into space and coming back down to earth! Motu then saves the day (and patlu from danger) while officer Chingnam arrests him and puts him in his jail called the web since Nobody could escape chingnam's web. In conclusion motu patlu has many elements many modern day animes don't have (I'm looking at you richard and mortimer) heart, an unstoppable duo, character arcs and development and who could forget Anime Betrayals. I give this anime 11 samosas out of 10! I am hyped for the next episode of Motu Patlu it's gonna be great!",
    "chutki": "chutki is fucking cringe. she is the most generic fucking character ive ever seen.",
    "tun": "devy and shifa we are still waiting on the om x dholu fanfic <:eboy:844132023224107018>",
    "dio": "joseph is better stfu ",
    "dutta": f"man when are you gon fight with disha again. we are seriously looking forward to the next fight {'<:technically:847106049935671357>' * 3}",
    "unplayable": "ffs if you say that again i will steal one of your terracotta elephants",
    "roy": "man black ops 1 is such a cringe game i uninstalled it bcoz there was an amogus reference in the game <:trollge:845728232119730186>",
    "dholu": "<:dukh:844185997678870559><:dard:844131868190048267>",
    "bholu": f"<:hmm:838812033759707176><:op:844131961949388841><:op:844131961949388841>",
    "bri'ish": "so you call these things 'chips'? instead of crispity crunchy munchie crackerjack snacker nibbler snap crack n pop westpoolchestershireshire queen's lovely jubily delights? That's rather bit cringe, innit bruv <:hmm:838812033759707176><:hmm:838812033759707176><:hmm:838812033759707176>",
    "technically": "<:technically:847106049935671357>" * 10,
    "1984": "LiTeRaLlY nInEtEeN eIgHtY-fOuR - George Orwell, 1948",
    "based": """Based? Based on what? On your dick? Please shut the fuck up and use words properly you fuckin troglodyte, do you think God gave us a freedom of speech just to spew random words that have no meaning that doesn't even correllate to the topic of the conversation? Like please you always complain about why no one talks to you or no one expresses their opinions on you because you're always spewing random shit like poggers based cringe and when you try to explain what it is and you just say that it's funny like what? What the fuck is funny about that do you think you'll just become a stand-up comedian that will get a standing ovation just because you said 'cum' in the stage? HELL NO YOU FUCKIN IDIOT, so please shut the fuck up and use words properly.""",
    "weeb": f"""You will never be Japanese. You have no ancestry, you have no citizenship, you have no skills that would make Japan ever want you. You are a shut-in self-hating white man twisted by delusions of mythical Japanese superiority and exposure to Japanese media into a disgusting mockery of nature’s perfection. All 'validation' you get from other people in this position couldn't be worse in making you believe that spending years of your life learning a globally useless language to a first-grader's level was a worthwhile use of your time, but one can't expect that an individual as pathetic as you will ever know the value of the youth you threw away in doing that. Actual Japanese are utterly repulsed by you. Thousands of years of linguistic evolution have allowed natives to identify frauds from mannerisms and vocabulary alone. Even if your written text of self-hatred and attention begging akin to a stray dog's somehow passes as normal (it won't), any Japanese person will immediately cut all ties when they hear the voice and accent of someone who is not only a basic Japanese speaker at best, but worth no more than garbage in skills, accomplishments, and likeability. You will never be happy. You wrench out a fake smile and laugh to yourself believing that watching a content creator that you understand 20% of at best is somehow superior than watching your own kind, as you project your disgusting traits onto your entire kind. However, deep inside you feel the depression creeping up like a weed, ready to crush you under the unbearable weight, and you know that. You know that all you do now is have an entirely new linguistic medium in which to be ignored, and not even the exotic trait of being foreign makes up for just how uninteresting of a person you are. yeah im talking to you. fucking cringe weaboo""",
    "krunker": "Krunker.io Akimbo 🔫👩 Uzi 🔫 is a two-handed automatic 🤖 weapon 🔫🏹. Many 🔢 players 🎮 prefer 👍🙋 this weapon ❌🔫🔪 because it can fire 🔥 quickly 🏃🏻💨. Detailed features 🎥 of this weapon 🗡 will be mentioned 🌲👇🏼🚘 below 👇🏻. The best 👌 thing 🕑 about 💦 a 3D 🤩‼ FPS 🔫🖱💣 gun 🔫 game 🎮 is that you 👈 will enjoy 👌🏽💯😌 a lot 💯🔥 of action 🎭. Not only that but 🍑 you 👉💦 will get 🉐 access 🔖 to various 🤓🧐 types ⌨ of weapons 🗡⚔ that can be used 🎶 inside 💠 the game 🎱📛. All 💯 these weapons 🔫🏹 have their benefits 👍 for drawbacks. Once you 👈🏼 understand ❓📚 the use 🏻 of these weapons 🗡🚮 in you 👈🏻 will surely 👍 love 😳❤ playing 🎮 with it. You 👉 can easily 👅 find 🔎 information ℹ🗺 about 💦 Krunker.io Akimbo 🔫👩 Uzi 🔫 which is a great 👍🏼👌🏼 weapon 🗡🔫💣 for close 🚫💦 combat 🗡🔫🏹. There are different ⁉ types ⌨ of things 🕑 that you 👉😘 can enjoy 👌💯 when ⏰ you 👈 use 😏 the Uzi 🔫 in the game 🎮🎲. It is a great 🇬🇧 weapon 🔫🏹 that is loved ❤ by most people 👬👫👭 for its firing 🔫🔥 speed 🏎👺💨 and dual-wielding ability 💪.",
    "jonathan": f"""haha Johnathan, you are banging my daughter. ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⣤⣤⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣴⣤⣤⣤⣴⣾⣿⣿⣿⣿⡄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠠⠾⢿⣿⣿⠟⠋⠁⠤⣬⣽⣿⡇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⡄⠄⠄⢀⣽⣦⡎⠁⠒⠒⢻⣿⣿⣄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⢀⣧⡀⢀⣾⣿⣿⣧⣦⣴⣾⣿⣿⣿⣿⣧⠄⠄⣠⣴⣆⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⡻⣿⣿⣿⣿⣧⢸⣿⣿⣿⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠘⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣸⣿⣿⣿⣿⣿⣿⣿⣝⣿⡟⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠸⣄⢺⣿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡏⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⢿⠄⡀⠄⣸⣿⡿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠸⡆⠄⣀⣛⣫⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠇⠄⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠐⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢹⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⠿⠽⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢸⣿⣿⣿⡿⠟⠛⠉⠄⠄⠄⠄⠄⠄⠄⠄""",
    "bad": """⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣤⣶⣶⣶⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⡿⡱⡿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⢰⣿⣿⣿⣿⡟⠟⠛⠁⠄⠂⠀⠓⠋⢟⣿⣿⣿⣿⣿⣇⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⣿⣿⠜⢖⣁⣀⣀⡀⠀⢀⣐⢠⣴⣟⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⣿⣷⣛⠿⠻⠉⠯⣉⠠⠹⠚⠺⠿⢿⣟⣿⣿⣿⣿⠀⠀⠀⠀⠀ ⠀⠀⠀⢐⣿⣿⡿⡿⣿⣷⠆⠀⠐⠀⠀⠀⠀⢠⣼⣶⣿⣿⣿⣿⣿⡶⠀⠀⠀⠀ ⠀⠀⠀⠘⣿⡟⠻⣋⢉⣉⠁⣀⢀⣄⣠⣄⡀⠀⣉⣉⣙⠻⢻⣿⣿⡷⠀⠀⠀⠀ ⠀⠀⠀⠀⣿⣿⣾⡏⠑⠓⠉⢉⣾⣿⣿⣿⣯⠑⠚⠓⢛⣾⣼⣿⣿⡇⠀⠀⠀⠀ ⠀⠀⠀⠀⢹⣿⡿⠻⠠⢤⣔⣼⣿⣿⣾⣿⣿⣲⣄⠀⠘⠻⣿⣿⡟⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠘⣿⣧⠀⣀⠟⠃⠡⣿⠿⠞⠽⣿⠈⠛⣶⣀⣇⣿⡿⠃⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⢹⣿⣾⣯⠃⢠⣴⣦⠀⠀⣠⣴⣦⡀⠘⣿⡷⣿⠁⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⣿⣾⡇⢠⡿⡿⠻⠁⢠⠸⠻⢿⢷⠀⢸⣿⠏⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠘⣿⡇⠊⣠⣤⣤⣤⣤⣶⣦⣤⣀⠃⣾⡟⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠘⣧⣬⡶⠀⠀⠀⠀⠀⠀⠸⣿⣦⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣿⣿⡿⡛⢟⢶⣶⣽⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠿⢶⣴⡿⠟⠋⠀⠀⠀⠀""",
    "good": "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⢄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠖⠁⠀⠀⠀⠀⠀⠈⠋⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⣠⣾⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠙⢦⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⢠⣿⡿⢁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠸⣷⣀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⣿⣿⡧⢕⠂⠀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⠀⣿⣿⡄⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⣿⠏⠃⠈⠉⠀⠀⠀⠀⠀⠀⠈⠈⠀⠀⠀⠐⣿⣿⡇⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⣿⣿⣿⣴⣶⡆⠀⠀⠀⠀⠀⠀⠀⣴⣴⣴⣄⣿⣿⣇⠀⠀⠀⠀ ⠀⠀⠀⠀⣿⣿⣿⣦⣤⣤⠌⣻⣦⣤⡀⢀⣤⡠⢔⡀⢀⣀⣉⢻⢿⣿⠇⠀⠀⠀ ⠀⠀⠀⠀⢿⣿⠋⡟⠙⠛⠚⠘⠋⢉⠁⠈⠙⠋⠃⠿⠟⠛⠩⠹⣿⡿⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⡎⡐⠙⠓⠚⠉⠠⣾⡆⠀⢰⠀⠒⠒⠒⠂⡀⢺⣿⠇⠀⠀⠀⠀ ⠀⠀⠀⠀⢸⣿⣿⡁⠀⠀⠀⡤⠔⡎⠂⠀⠈⡖⣀⡀⠀⠀⠨⠄⢿⠂⠀⠀⠀⠀ ⠀⠀⠀⠀⠈⣷⣿⣧⣠⡖⠁⠀⣿⣧⣀⣀⣠⣷⠀⠉⢦⣤⣤⣷⡗⠁⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⢻⣸⠉⠛⢿⣶⣄⡨⠻⢿⣿⣿⣅⣄⣶⣾⠿⠛⣿⡇⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠘⢿⣦⠀⠀⠈⠻⢍⠙⠉⠋⠋⠉⡿⠋⠀⠀⣼⡿⠁⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠈⠞⣦⠀⢬⢧⣄⣀⡁⠉⣀⣠⡽⠁⠀⡼⠅⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠻⣧⣄⡉⠛⠛⠛⠛⠛⠋⠀⢠⣼⠋⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠻⣷⡄⠈⠀⠀⢀⢀⣤⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠻⠶⠼⠟⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀",
    "china": "⣿⣿⣿⣿⣿⠟⠋⠄⠄⠄⠄⠄⠄⠄⢁⠈⢻⢿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⡀⠭⢿⣿⣿⣿⣿ ⣿⣿⣿⣿⡟⠄⢀⣾⣿⣿⣿⣷⣶⣿⣷⣶⣶⡆⠄⠄⠄⣿⣿⣿⣿ ⣿⣿⣿⣿⡇⢀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠄⠄⢸⣿⣿⣿⣿ ⣿⣿⣿⣿⣇⣼⣿⣿⠿⠶⠙⣿⡟⠡⣴⣿⣽⣿⣧⠄⢸⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣾⣿⣿⣟⣭⣾⣿⣷⣶⣶⣴⣶⣿⣿⢄⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⡟⣩⣿⣿⣿⡏⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣹⡋⠘⠷⣦⣀⣠⡶⠁⠈⠁⠄⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣍⠃⣴⣶⡔⠒⠄⣠⢀⠄⠄⠄⡨⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣦⡘⠿⣷⣿⠿⠟⠃⠄⠄⣠⡇⠈⠻⣿⣿⣿⣿ ⣿⣿⣿⣿⡿⠟⠋⢁⣷⣠⠄⠄⠄⠄⣀⣠⣾⡟⠄⠄⠄⠄⠉⠙⠻ ⡿⠟⠋⠁⠄⠄⠄⢸⣿⣿⡯⢓⣴⣾⣿⣿⡟⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⠄⣿⡟⣷⠄⠹⣿⣿⣿⡿⠁⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⣸⣿⡷⡇⠄⣴⣾⣿⣿⠃⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⠄⣿⣿⠃⣦⣄⣿⣿⣿⠇⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄ ⠄⠄⠄⠄⠄⢸⣿⠗⢈⡶⣷⣿⣿⡏⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄",
    "gav": "joe biden. joe biden. joe biden. joe biden. this message from mohammad khanaqin, full face of kurdistan, for you, joe biden. you go check up on a doctor, you have 2 yil. your life is 2 yil. 2 yil from now, from today, to 2 yil uh 1 yil in 6 months. 2 yil. your life. after this one you will pass away. you go check up on a doctor, this message from mohammad khanaqin, full face of kurdistan. you do - do you - good job for the usa for the [unintelligible] in 2 yil, you do [unintelligible] you wanna kurdistan cannon, new country, no more iran, no more iraq, no more turkey, no more syria. full face of kurdistan will give you-",
    "bhatta": "Need robux to fund boblos empire. Pls donate ⣿⣿⣿⣿⣿⡿⠿⠻⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⠿⠻⠻⠟⠻⢿⣿⣿⣿⣿ ⣿⣿⡟⠁⢀⣠⣤⣤⣤⣤⣄⣀⣀⣀⣹⣿⣿⣷⣄⣀⣀⣀⣀⣤⣤⣤⣤⣀⠐⢽⣿⣿⣿ ⣿⣿⣿⣶⣿⡿⣛⡒⠒⠒⢒⠒⣲⠙⣿⣿⣿⣿⠟⣵⡒⢒⠒⠒⡀⣘⡻⣿⣿⣾⣿⣿⣿ ⣿⣿⣿⣿⣏⣞⡛⠃⠀⠀⠸⠷⢿⣧⣿⣿⣿⣿⣧⣿⣷⣛⣀⣀⣁⣛⣛⣮⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢏⣾⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢻⣿⠏⣼⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠟⢛⣉⣴⣿⡏⣸⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣧⣠⣤⣤⣤⣤⣤⣤⣶⣶⣶⣶⣿⣿⣿⣿⣿⠃⣿⣿⣿⣿⣿⣿⣿ ⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣿⣿⣿⣿⣿⣿⣿",
    "kpop": "imagine instead of kpop it was rpop and it’s from Russia and you had girls all over twitter being like “Stream Я какала вщтань” and posting pictures going “OMG lvonovativich looks so CUTE” \n\nimagine if instead of kpop it was dpop and it's from germany and you had girls all over Twitter being like 'stream Donau­dampf­schiffahrts­elektrizitäten­haupt­betriebs­werk­bau­unter­beamten­gesellschaft' and posting pictures like this and being like 'OMG Rudolf looks so CUTE' \n\nimagine if instead of kpop it was bpop and it's from Brazil and you had girls all over Twitter being like 'stream Comi o cu de quem tá lendo' and posting pictures like this and being like 'OMG Ayrton looks so CUTE'",
    "hentai": "Watashi wa 👅 a 👌 victim of 💦 cyberbullying. Everyday 🗓 someone 👤 online 💻 calls 🗣 me 😭 a 👌 'weeb' desu. 👌 Watashi won't 🚫 stand 💨 for 🍆 this. 👈 26 percent 🔟 of 💦 bullying 😂 victims are 🔢 chosen due to 💦 their 🍆 race 🖕 or 💁 religion 🕋 desu. 👌 I 👁 may 🗓 look 👀 like 💖 a 👌 basic 🚂 white 👱 boy, 👦 but 🍑 deep 😱 down 🔻 I 👁 am 👏 Nihongo desu. 👌 Watashi religion 🕋 is 💦 anime. 😹 Anata wa 👅 bullying 😂 me 😭 because 💁 of 💦 my 👨 race 🖕 and 👏 religion 🕋 desu 👌 ka? Disgusting 😝 desu. 👌 Anata should 💘 be 🐝 ashamed 😳 of 💦 yourself, 🙄 pig. A 👌 baka gaijin like 💖 anata is 💦 probably 😻 jealous 😒 of 💦 my 👨 race 🖕 and 👏 culture, cause 💋 Nippon is 💦 more 🍗 sugoi than 👉 your 👏 shitty 💩 country 🏃 desu. 👌 Watashi pity 😢 anata. You'll 👉 never 🙅 be 🐝 Nihongo like 💖 watashi. I'm 💘 a 👌 weeb? Pfft. I 👁 AM 👏 AN 👹 OTAKU DESU. 👌 Educate yourself 🙄 on 🔛 nani a 👌 'weeb' is 💦 before 😂 anata try 😐 to 💦 insult 😦 watashi desu. 👌 I 👁 WILL 👏 NOT 🚫 BE 🐝 CYBERBULLIED ANYMORE. 🔥 REPORTED. Arigatou 💘 for my first gold💦 and silver🔥 , Stranger sama💋 👅",
    "i use arch btw": """
							Listen you filthy winbloats normie, you're probably used to sucking off proprietary dicks with all proprietary bullshit that's on your computer. I, being the obvious next evolution of you, use GNU/Linux. My computer is a beautiful peace of Free and Open Source Software, or as I've recently started calling it Libre Software.

Last time I checked I didn't have cortana bloat spying on me like the fucking Microsoft SIMP she is. If Jesus was an OS he would definitely be GNU/Linux. In ancient scribes found in the library of Alexandria, it has been proven that the GNU/Linux is better than winbloats. Since then the most popular porn site has been r/unixporn

Enjoy your normie life as winbloats user while my GNU/Linux runs a helicopter on mars as well as a toaster in my kitchen. My whole life is FOSS and I am now more FREE than America.
							  """,
    "dirty deeds done dirt cheap": "Suppose that you were sitting down at this table. The napkins are in front of you, which napkin would you take? The one on your ‘left’? Or the one on your ‘right’? The one on your left side? Or the one on your right side? Usually you would take the one on your left side. That is ‘correct’ too. But in a larger sense on society, that is wrong. Perhaps I could even substitute ‘society’ with the ‘Universe’. The correct answer is that ‘It is determined by the one who takes his or her own napkin first.’ …Yes? If the first one takes the napkin to their right, then there’s no choice but for others to also take the ‘right’ napkin. The same goes for the left. Everyone else will take the napkin to their left, because they have no other option. This is ‘society’… Who are the ones that determine the price of land first? There must have been someone who determined the value of money, first. The size of the rails on a train track? The magnitude of electricity? Laws and Regulations? Who was the first to determine these things? Did we all do it, because this is a Republic? Or was it Arbitrary? NO! The one who took the napkin first determined all of these things! The rules of this world are determined by that same principle of ‘right or left?’! In a Society like this table, a state of equilibrium, once one makes the first move, everyone must follow! In every era, this World has been operating by this napkin principle. And the one who ‘takes the napkin first’ must be someone who is respected by all. It’s not that anyone can fulfill this role… Those that are despotic or unworthy will be scorned. And those are the ‘losers’. In the case of this table, the ‘eldest’ or the ‘Master of the party’ will take the napkin first… Because everyone ‘respects’ those individuals.",
}

amogus_copypasta: List[str] = [
    "It’s just a sussy baka and it cannot be that bad. I’m feeling like👹imposter👹I might just be a monster😨😨😨Feeling ☺️kinda crew...😳Got many tasks🔨🔦🔌To do🤨🤨",
    "This game has ruined my fucking life. I'm going to end it and take you all with me because I can't bear to look at anything anymore. Any shape I see is distorted into amogus, any time I hear the word suspicious, sus, task, vent, report, ANYTHING, human pattern recognition turns it into amogus. I close my eyes and i see amogus, i see jerma985 grinning as the gates of my soul are opened by amogus and I can feel the festering sclunge of words and shapes pour in, filling all that I am with the ringing noise of amogus",
    "‼️‼️HOLY FUCKING 🖕👦 SHIT‼️‼️‼️‼️ IS THAT A MOTHERFUCKING 👩💞 AMONG 💰 US 🇺🇸 REFERENCE??????!!!!!!!!!!11!1!1!1!1!1!1 😱! 😱😱😱😱😱😱😱 AMONG 💑👨‍❤️‍👨👩‍❤️‍👩 US 👨 IS THE BEST 👌💯 FUCKING 💦🍆👀 GAME 🎮 🔥🔥🔥🔥💯💯💯💯 RED 🔴 IS SO SUSSSSS 🕵️🕵️🕵️🕵️🕵️🕵️🕵️🟥🟥🟥🟥🟥 COME 💦🏃🏃‍♀️ TO MEDBAY AND WATCH 👀 ME SCAN 👀 🏥🏥🏥🏥🏥🏥🏥🏥 🏥🏥🏥🏥 WHY 😡🤔 IS NO ⚠🚫 ONE 1️⃣ FIXING 👾 O2 🅾 🤬😡🤬😡🤬😡🤬🤬😡🤬🤬😡 OH 🙀 YOUR 👉 CREWMATE? NAME 📛 EVERY 💯 TASK 📋 🔫😠🔫😠🔫😠🔫😠🔫😠 Where Any sus!❓ ❓ Where!❓ ❓ Where! Any sus!❓ Where! ❓ Any sus!❓ ❓ Any sus 🌈🏳️‍🌈! ❓ ❓ ❓ ❓ Where!Where!Where! Any sus!Where!Any sus 🌈🏳️‍🌈 Where!❓ Where! ❓ Where!Any sus❓ ❓ Any sus 💦! ❓ ❓ ❓ ❓ ❓ ❓ Where! ❓ Where! ❓ Any sus!❓ ❓ ❓ ❓ Any sus 🌈🏳️‍🌈! ❓ ❓ Where!❓ Any sus 💦! ❓ ❓ Where!❓ ❓ Where! ❓ Where!Where! ❓ ❓ ❓ ❓ ❓ ❓ ❓ Any sus!❓ ❓ ❓ Any sus!❓ ❓ ❓ ❓ Where! ❓ Where! Where!Any sus!Where! Where! ❓ ❓ ❓ ❓ ❓ ❓ I 👥 think 🤔 it was purple!👀👀👀👀👀👀👀👀👀👀It wasnt me I 👁 was in vents!!!!!!!!!!!!!!😂🤣😂🤣😂🤣😂😂😂🤣🤣🤣😂😂😂",
    "It seems like the more I (13 M) play Amongus, the more my family tries to embaras me. The other day, I overheard my dad (49 M) say that he needed to 'complete tasks' while working at home😯🤬 don't worry it gets worse. Then I hear my Mom (42 F) say that the amount of time I spend on my computer is 'suspiscios.' Ummm ok so (#1) ur too good to say 'sus' 🤔 and (#2) u dont even play amogus??? 😂😂😂. Even my moms work friend (28 M or somthing idk) came over yesterday to 'look at her vents' I'm not even making this up 🙄🙄🙄 But then the worse part😑 every sunday my granpa (69 M) comes over. He reminisces about his 'Crewmates' from his Navy days and apparently a few of them died so u cry about it at dinner? Just start a new game FFS 😆 but he's lying so uhhh we get it bro: u just want attention 😯😅🤣The problem is NONE of them even Play Omungus. How do i tell em that being a poser is a cringe Brie Larson unholesome Black History Month anti-chungus move?",
    "📮📮 📮 📮 📮📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮 📮📮 📮📮📮 📮📮 OMG GUYS🤯🤯🤯!!!! THE MAILBOX IS AN IMPOSTER📮😂🤣🤣🤣😳!!! HE IS SO SUS!!!! (THIS IS A REFERENCE TO THE POPULAR MOBIL AND COMPUTER GAMG AMONG US) 🤣🤣😳😳😂😂😂😂😝😝😝📮😳",
    "I am a concerned mother with a 13 year old child and I am here to seek help regarding my son. Last week when we went to the supermarket, my son pointed to a red trash can and started jumping around screaming “THAT’S AMONG US! THAT TRASH CAN IS SUS! RED IS THE IMPOSTOR!” As soon as he did that, the manager told us to leave. I told him that my son is just excited about something, and apologised. But the manager still told us to leave so I picked up the red trash can that my son was going crazy over and threw it on the managers head. Then my son shouted “DEAD BODY REPORTED.” Can someone please tell me what on earth is wrong with him?",
    "My name is Yoshimpostor Amogus. I'm 33 years old. My house is in the northeast section of Electric, where all the wirings are, and I am not sus. I work as a crewmate for the Space Ship, and I get to the cafeteria every day by 8 PM at the latest. I don't sabotage, but I occasionally vent. I'm in Cameras by 11 PM, and make sure I get eight hours of vigilance, no matter what. After having a glass of warm milk and doing about twenty minutes of stretches before going to bed, I usually have no problems sleeping until morning. Just like a crewmate, I wake up without any fatigue or stress in the morning. I was told there were no issues at my last scan. I'm trying to explain that I'm a person who wishes to live a very quiet life. I take care not to trouble myself with any enemies, like winning and losing, that would cause me to lose sleep at night. That is how I deal with socity, and I know that is what brings me happiness. Although, if I were to evict I wouldn't lose to anyone.",
    "I can't fucking take it. I see an image of a random object posted and then I see it, I fucking see it. \"Oh that looks kinda like the among us guy\" it started as. That's funny, that's a cool reference. But I kept going, I'd see a fridge that looked like among us, I'd see an animated bag of chips that looked like among us, I'd see a hat that looked like among us. And every time I'd burst into an insane, breath deprived laugh staring at the image as the words AMOGUS ran through my head. It's torment, psychological torture, I am being conditioned to laugh maniacly any time I see an oval on a red object. I can't fucking live like this... I can't I can't I can't I can't I can't! And don't get me fucking started on the words! I'll never hear the word suspicious again without thinking of among us. Someone does something bad and I can't say anything other than \"sus.\" I could watch a man murder everyone I love and all I would be able to say is \"red sus\" and laugh like a fucking insane person. And the word \"among\" is ruined. The phrase \"among us\" is ruined. I can't live anymore. Among us has destroyed my fucking life. I want to eject myself from this plane of existence. MAKE IT STOP!",
]

image_easter_eggs: Dict[str, str] = {
    "dababy": "https://i.imgur.com/ymVKI46.jpg",
    "stuff": "https://i.redd.it/tvcz6r7q2p371.png",
    "anon": "https://i.kym-cdn.com/photos/images/facebook/001/038/495/f0f.png",
    "who asked": "https://i.imgur.com/dwJBMBp.jpeg",
    "mutahar": "https://i.redd.it/kuqqdjtiyz471.jpg",
    # warning, the below gif link is NSFW and is only meant as a joke.
    "boat talks": "https://media.discordapp.net/attachments/838803234390802516/853327866145407036/ezgif.com-gif-maker.gif",
}